name: Snyk Code Scan with Blocking

on:
  push:
    branches:
      - master  # Cambia a la rama principal de tu proyecto si es distinta
  pull_request:
    branches:
      - main

jobs:
  snyk-code-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Cambia a la versión de Node.js que usa tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Run Snyk Code Test
        uses: snyk/actions/node@v3
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: code test
        continue-on-error: false  # Se asegura de que el pipeline falle si se detecta una vulnerabilidad

      - name: Fail if vulnerabilities are found
        if: failure()
        run: exit 1
